#!/bin/bash
# Needs to run under bash as other shells seem to mangle embedded \n line terminators
#
for f in `find $1 -name ".git"`; do
  dir=$(dirname $f)
  patch=`git -C $dir --no-pager diff`
  if [ "$patch" != "" ]; then
    echo "############ $(basename $dir) ############"
    echo "echo Patching $dir"
    echo "git -C $dir checkout ."
    echo "patch -p1 -d $dir <<'EOF'"
    echo "$patch"
    echo EOF
  fi
done