#!/bin/bash
for f in `find -name ".git"`; do
  dir=$(dirname $f)
  patch=`git -C $dir --no-pager diff`
  if [ "$patch" != "" ]; then
    echo "echo $dir"
    echo "git -C $dir checkout ."
    echo "patch -p1 -d $dir <<'EOF'"
    echo "$patch"
    echo EOF
  fi
done